apiVersion: v1
kind: ConfigMap
metadata:
  name: d32-release-dev-app-config
  namespace: d32-release-dev
data:
  APP_ENV: "dev"
  # For first EKS tests, keep LLM cost zero:
  USE_MOCK_LLM: "true"
  # Set this to the Redis endpoint from Terraform, without scheme & port.
  # Example: d32-release-dev-redis.xyz.cache.amazonaws.com
  REDIS_URL: "redis://${REDIS_ENDPOINT}/0"
